package globalization

const (
	ArgentinaCountryCode         = "ar"
	BoliviaCountryCode           = "bo"
	BrazilCountryCode            = "br"
	ChileCountryCode             = "cl"
	ColombiaCountryCode          = "co"
	CostaRicaCountryCode         = "cr"
	CubaCountryCode              = "cu"
	DominicanRepublicCountryCode = "do"
	EcuadorCountryCode           = "ec"
	ElSalvadorCountryCode        = "sv"
	GuatemalaCountryCode         = "gt"
	HondurasCountryCode          = "hn"
	MexicoCountryCode            = "mx"
	PanamaCountryCode            = "pa"
	ParaguayCountryCode          = "py"
	PeruCountryCode              = "pe"
	UruguayCountryCode           = "uy"
	UnitedStatesCountryCode      = "us"
	VenezuelaCountryCode         = "ve"

	AmericaBuenosAiresTimeZone  = "America/Buenos_Aires"
	AmericaSantiagoTimeZone     = "America/Santiago"
	AmericaLaPazTimeZone        = "America/La_Paz"
	AmericaBogotaTimeZone       = "America/Bogota"
	AmericaCostaRicaTimeZone    = "America/Costa_Rica"
	AmericaHavanaTimeZone       = "America/Havana"
	AmericaSantoDomingoTimeZone = "America/Santo_Domingo"
	AmericaGuayaquilTimeZone    = "America/Guayaquil"
	AmericaElSalvadorTimeZone   = "America/El_Salvador"
	AmericaGuatemalaTimeZone    = "America/Guatemala"
	AmericaTegucigalpaTimeZone  = "America/Tegucigalpa"
	AmericaMexicoCityTimeZone   = "America/Mexico_City"
	AmericaPanamaTimeZone       = "America/Panama"
	AmericaAsuncionTimeZone     = "America/Asuncion"
	AmericaLimaTimeZone         = "America/Lima"
	AmericaMontevideoTimeZone   = "America/Montevideo"
	AmericaNewYorkTimeZone      = "America/New_York"
	AmericaCaracasTimeZone      = "America/Caracas"
	AmericaSaoPauloTimeZone     = "America/Sao_Paulo"
)

